/*
 * TAAG-AT/Api/v1/Etudiants
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * DetailsMetierDataAttributesCompetencesAttributes
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-10-30T17:21:14.807Z[GMT]")
public class DetailsMetierDataAttributesCompetencesAttributes {
  @SerializedName("titre")
  private String titre = null;

  @SerializedName("description")
  private String description = null;

  public DetailsMetierDataAttributesCompetencesAttributes titre(String titre) {
    this.titre = titre;
    return this;
  }

   /**
   * Get titre
   * @return titre
  **/
  @Schema(description = "")
  public String getTitre() {
    return titre;
  }

  public void setTitre(String titre) {
    this.titre = titre;
  }

  public DetailsMetierDataAttributesCompetencesAttributes description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  @Schema(description = "")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DetailsMetierDataAttributesCompetencesAttributes detailsMetierDataAttributesCompetencesAttributes = (DetailsMetierDataAttributesCompetencesAttributes) o;
    return Objects.equals(this.titre, detailsMetierDataAttributesCompetencesAttributes.titre) &&
        Objects.equals(this.description, detailsMetierDataAttributesCompetencesAttributes.description);
  }

  @Override
  public int hashCode() {
    return Objects.hash(titre, description);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DetailsMetierDataAttributesCompetencesAttributes {\n");
    
    sb.append("    titre: ").append(toIndentedString(titre)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
