/*
 * TAAG-AT/Api/v1/Etudiants
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.ReqConnexion;
import io.swagger.client.model.ReqInscription;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for AuthentificationApi
 */
@Ignore
public class AuthentificationApiTest {

    private final AuthentificationApi api = new AuthentificationApi();

    /**
     * Eenregistrement d&#x27;un étudiant
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void apiElevesV1EnregistrementsPostTest() throws ApiException {
        ReqInscription body = null;
        api.apiElevesV1EnregistrementsPost(body);

        // TODO: test validations
    }
    /**
     * Connecte un étudiant à l&#x27;api taag
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void apiElevesV1SessionsPostTest() throws ApiException {
        ReqConnexion body = null;
        api.apiElevesV1SessionsPost(body);

        // TODO: test validations
    }
}
