/*
 * TAAG-AT/Api/v1/Etudiants
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.DetailsMetier;
import io.swagger.client.model.DetailsSecteur;
import io.swagger.client.model.ListeSecteurs;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for MtiersApi
 */
@Ignore
public class MtiersApiTest {

    private final MtiersApi api = new MtiersApi();

    /**
     * Détails Métier
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void apiElevesV1MetiersIdGetTest() throws ApiException {
        String id = null;
        DetailsMetier response = api.apiElevesV1MetiersIdGet(id);

        // TODO: test validations
    }
    /**
     * Liste  des secteurs d&#x27;activité avec 3 métiers
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void apiElevesV1SecteursGetTest() throws ApiException {
        ListeSecteurs response = api.apiElevesV1SecteursGet();

        // TODO: test validations
    }
    /**
     * Détails d&#x27;un secteur d&#x27;activité
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void apiElevesV1SecteursIdGetTest() throws ApiException {
        Integer id = null;
        DetailsSecteur response = api.apiElevesV1SecteursIdGet(id);

        // TODO: test validations
    }
}
